### ISSUE TITLE
Upper and lower tip radius from tipped disc tool

### ISSUE THREAD

**Issue by Feuerbowle** [Autodesk/PowerShapeAndPowerMillAPI#24]
At the moment the PMToolTippedDisc class only contain the .TipRadius method, which gets or sets only the lower tip radius of the tool.

I have extended the PMToolTippedDisc.cs with the appropriate functions, but since i'm new to github i'm not sure how to continue to submit this change.

**Comment by lukeedw** [comment]
Hi!!  Thanks for the update.  Before we can take your submission would you be able to sign one of the contributor agreements?  Follow the instructions here:
https://github.com/Autodesk/PowerShapeAndPowerMillAPI/blob/master/Contribute.md

**Comment by lukeedw** [comment]
Once you have done this, just commit your code into your fork and then create a Pull Request using the tools at the top of this page.

**Comment by Feuerbowle** [comment]
OK, done and done. Hopefully i've done everything correct

**Comment by lukeedw** [comment]
Great, thanks!
